site_name: safestructures
site_url: https://github.com/rachthree/safestructures
site_author: Craig Chan
site_description: Serialize general data structures with `safetensors`

repo_name: rachthree/safestructures
repo_url: https://github.com/rachthree/safestructures

copyright: Copyright (c) 2024-present Craig Chan

theme:
  name: readthedocs


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - mkdocstrings:

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/safestructures/
    - icon: fontawesome/brands/github
      link: https://github.com/rachthree

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Usage: usage.md
  - Why safestructures?: why_safestructures.md
  - Examples: examples.md
  - Reference:
      - safejax.core.load: api/core_load.md
      - safejax.core.save: api/core_save.md
      - safejax.utils: api/utils.md
  - License: license.md
