name: Build and Deploy Docs
on:
  workflow_call:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Get safestructures
        uses: actions/checkout@v4

      - name: Install safestructures with docs dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[docs]"

      - name: Deploy to Github pages
        run: mkdocs gh-deploy --force
